### ISSUE TITLE
Just an idea ... 

### ISSUE THREAD

**Issue by pieroproietti** [quirinux-so/instalar-quirinux#110]
Good morning Charles

I have recently included in eggs the concept of **costume** and **wardrobe**, to simplify 
- or try to simplify - the birth of new versions of Linux.

A costume is - at the moment - a simple directory with an index.yml file where the various 
operations to do to customize a distro are specified.

The central part is the concept of sequence:

```
sequence:            
  repositories:            # Operations on repositories
    sourcesList:           # include/exclude main, contrib, non-free
      main: true
      contrib: true
      nonFree: false
    sourcesListD:          # array of commands to add others repositories in /etc/apt/source.list.d
    # commands to add repositories

    update: true
    full-upgrade: true
  
  dependencies             # list of dependencies to install before
  - list dependencies

   firmware:               # list of firmware to install
   - list firmware

  packages:                # list of packages to install
  - list packages
  packagesPip:             # using pip to install python packages
   - pyclip                # pyclip in this example
    
  debs: false              # you can add a dir named debs and all *.deb inside will be installed
  dirs: true               # /dirs will be copied to /, /dirs/etc/skel will be copied to user home too
  hostname: true           # will change hostname with the costume name
  customizations:          # costomization
    scripts:               # for example I use this to copy android images inside the system
    - list of scripts
  reboot: true
...
```
I experimented a bit with gwaydroid - a version of linux with gdm3 and waydroid, then fell back on hen the configuration I always use to develop eggs.

For hen, I've had great results, the outfit is complete though very simple, in the end it's just adding code, nodejs 16, firefox-esr and a custom xfce4 interface.

This morning I wanted to try your quirinux-so and I tried to install it, first in basic version and then in pro version.

Both attempts ended without the addition of a GUI - I wouldn't have expected that - it could be your design choice, so I installed on the PRO xfce4 and poked around your system a bit, just a short walk, not being at all knowledgeable about graphics and design.

Mostly, I went to see what you install and noticed a ton of firmware:
- driversNetworkWifi
- driversNetwork
- driversGraphicsCardNvidia
- driversGraphicsCardAmd
- driversGraphicsTabletGenius
- driversPrinterHP
- driversPrinterEpson

plus of course a whole series of specialized packages, I guess for video and graphics you need.

In defining a custome, I lacks firmware necessary for your pattern, or perhaps the capacity to divide
packages in:
```
packages-steps:
   dependecies:
   -
   firmware:
   -
   packages
   -
```

I was wondering: if I will go to insert the necessary steps, would you be interested in using it?

Vice versa, if I try to insert your firmware list in hen - personally I don't care - I always use a VM, would you have anything against it?

PS: I think I fixed the [bug](https://github.com/pieroproietti/penguins-eggs/issues/119) you reported, and added selection for all the languages and keyboards type on cli installer krill (sudo eggs install --cli) a simple and fast way to install you you don't need dual-boot.

I hope that can be interesting for you, anyway greetings from Rome.

**Comment by quirinux-so** [comment]
Great Piero, it will be a great help. I didn't include it in this code since it's more intended for end users who don't configure things (they use menus), however I'm already starting to use it in my tests.

**I have a question:** what happens if a package **does not exist?** 

In the tests I did, the script does not execute. As a control, this is interesting, although sometimes the number of packages that I put is many and that is why I made for loops in my script: so that apt continues installing despite that. 

Without a doubt, your program is more recommendable, since if something cannot be installed it is good to know and remove it _(or correct it)._ Though could we disable this so it installs anyway?

**Example:**

packages:
-kdenlive
-cinelerra _<- does not exist, never mind, install the ones that exist._

It would also be very useful to add something that my original script does not have: a _warning_, at the end, that lists all those missing packages. I don't know if I explain myself. 

All the best
:-)
Charlie

**Comment by pieroproietti** [comment]
Yes, you are right, probably adding something like:

```
for i in package1 package2 package3; do
  sudo apt-get install $i
done
```
can be usefull.
Actually - for example - I have problems with ubuntu vs debian dressing the same costume: one want ```firefox``` and other ```firefox-esr``` in this way we can add both.

Again better can be add a section: ```try_packages``` and ```try_packages_no_install_reccomend``` to use for that.

in that case we can:

```
    try_packages:
      - firefox
      - firefox_esr
```
And will work on debian and ubuntu.
